package com.bonpass.tests;

import com.bonpass.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selectors.byAttribute;
import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.open;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;

public class BonsellerAuthTest extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("BonSeller success login")
    void generatedTest() {
        step("Open https://dev.seller.bonpass.com/login", () -> {
            open("https://dev.seller.bonpass.com/login");
        });

        step("Set login as seller phone  «+7 900 900 50 50»", () -> {
            $(byAttribute("type", "tel")).setValue("+7 900 900 50 50");
        });

        step("Set password code for authorization «2508»", () -> {
            step("// todo: just add selenium action");
        });

        step("Submit form", () -> {
            step("// todo: just add selenium action");
        });

        step("Verify successful authorithation as seller", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://dev.seller.bonpass.com/login'", () ->
                open("https://dev.seller.bonpass.com/login"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}